/**
 * Init command - create a new agent configuration interactively.
 */

import { existsSync } from "node:fs";
import { writeFile, mkdir } from "node:fs/promises";
import { resolve, join } from "node:path";
import type { IAgentConfig } from "@openstarry/sdk";
import type { CliCommand, ParsedArgs } from "./base.js";
import { Prompter } from "../utils/prompts.js";

export interface InitPromptResult {
  name: string;
  description: string;
  provider: string;
  model: string;
  plugins: string[];
}

export class InitCommand implements CliCommand {
  name = "init";
  description = "Create a new agent configuration interactively";

  async execute(args: ParsedArgs): Promise<number> {
    // [Plan34 W3] --project flag: create .openstarry/ template directory
    if (args.flags["project"]) {
      return this.initProjectDir();
    }

    // 1. Check if agent.json exists
    const targetPath = resolve(process.cwd(), "agent.json");
    if (existsSync(targetPath) && !args.flags.force) {
      console.error(`agent.json already exists at ${targetPath}`);
      console.error(`Use --force to overwrite.`);
      return 1;
    }

    // 2. Interactive prompts
    console.log("Creating a new OpenStarry agent configuration...\n");
    const result = await this.promptUser();

    // 3. Generate config
    const config = this.generateConfig(result);

    // 4. Write to disk
    await writeFile(targetPath, JSON.stringify(config, null, 2), "utf-8");

    console.log(`\nAgent configuration created: ${targetPath}`);
    console.log(`Run 'openstarry start' to launch your agent.`);

    return 0;
  }

  private async initProjectDir(): Promise<number> {
    const target = process.cwd();
    const dotOpenstarryPath = join(target, ".openstarry");

    await mkdir(dotOpenstarryPath, { recursive: true });

    // Write config.json template
    const configTemplate = {
      identity: {
        description: "Project-specific agent description override",
      },
      cognition: {
        temperature: 0.7,
      },
    };
    await writeFile(
      join(dotOpenstarryPath, "config.json"),
      JSON.stringify(configTemplate, null, 2),
      "utf-8",
    );

    // Write permissions.json template
    // Note: no _comment field — ProjectPermissionsSchema uses .strict() (SEC-004)
    const permissionsTemplate = {
      allowedPaths: [],
      allowedTools: [],
      deniedTools: [],
      maxConcurrentTools: 1,
    };
    await writeFile(
      join(dotOpenstarryPath, "permissions.json"),
      JSON.stringify(permissionsTemplate, null, 2),
      "utf-8",
    );

    // plugins.json is NOT generated by default (KD-4: absent = no override).
    // An empty plugins array would fail ProjectPluginsSchema min(1) validation.
    // Users should create plugins.json manually when they need to override the plugin list.

    // Write README.md template (spec §十三 requirement)
    const readmeContent = `# .openstarry/ — Project Configuration

Configuration files in this directory are loaded ONCE when the agent starts.
Changes made while the agent is running have NO effect until the next restart.

## Files

- \`config.json\` — Non-security agent configuration (identity, cognition parameters).
- \`permissions.json\` — Security restrictions (restrict-only; cannot expand system permissions).
- \`plugins.json\` — Plugin list override (replaces the agent config plugin list entirely).

All files are optional. Omit any file to inherit the system-level setting.

## Disable

Run \`openstarry start --no-project-dir\` to ignore this directory for a single run.
`;
    await writeFile(join(dotOpenstarryPath, "README.md"), readmeContent, "utf-8");

    console.log(`[cli] Project configuration created at ${dotOpenstarryPath}`);
    return 0;
  }

  private async promptUser(): Promise<InitPromptResult> {
    const prompter = new Prompter();

    const name = await prompter.ask("Agent name", "MyAgent");
    const description = await prompter.ask("Description", "An OpenStarry AI agent");
    const provider = await prompter.ask("LLM provider", "gemini-oauth");
    const model = await prompter.ask("Model", "gemini-2.0-flash");

    prompter.close();

    return { name, description, provider, model, plugins: [] };
  }

  private generateConfig(result: InitPromptResult): IAgentConfig {
    return {
      identity: {
        id: result.name.toLowerCase().replace(/\s+/g, "-"),
        name: result.name,
        description: result.description,
        version: "0.1.0",
      },
      cognition: {
        provider: result.provider,
        model: result.model,
        temperature: 0.7,
        maxTokens: 8192,
        maxToolRounds: 10,
      },
      capabilities: {
        tools: ["fs.read", "fs.write", "fs.list"],
        allowedPaths: [process.cwd()],
      },
      policy: {
        maxConcurrentTools: 1,
        toolTimeout: 30000,
      },
      memory: {
        slidingWindowSize: 5,
      },
      plugins: [
        { name: "@openstarry-plugin/provider-gemini-oauth" },
        { name: "@openstarry-plugin/standard-function-fs" },
        { name: "@openstarry-plugin/standard-function-stdio" },
      ],
      guide: "default-guide",
    };
  }
}
