/**
 * snapshot-hmac — Plan47 K-3 wire-in HMAC + nonce integrity for checkpoint blobs.
 *
 * Responsibilities:
 *   - Sign a checkpoint payload with HMAC-SHA256 using a caller-supplied key
 *     (never stored in Core; supplied by env/CLI/plugin config — MR-6 compliance).
 *   - Verify signature on read with constant-time compare.
 *   - Generate and validate nonces for replay protection (each checkpoint file
 *     binds a fresh nonce; restore rejects duplicate nonces within a session
 *     via the NonceRegistry).
 *
 * This module lives at runner-level per Tenet #2 / MR-6: Core never sees the
 * HMAC primitive or the policy for key length, nonce length, or replay window.
 *
 * @since Plan47 (C47-K3-M1+M5 HMAC sync requirement, R3 D2.5 BABBAGE 翻轉)
 */

import { createHmac, randomBytes, timingSafeEqual } from 'node:crypto';

/** Length in bytes of a nonce generated by {@link generateNonce}. */
export const SNAPSHOT_NONCE_LENGTH_BYTES = 16;

/** Minimum accepted HMAC key length — enforced by the runner, not Core. */
export const SNAPSHOT_MIN_KEY_LENGTH_BYTES = 32;

/** HMAC algorithm used for checkpoint blob signing. */
export const SNAPSHOT_HMAC_ALGORITHM = 'sha256' as const;

/** Signature envelope emitted by {@link signSnapshotPayload}. */
export interface SnapshotSignatureEnvelope {
  readonly algorithm: 'sha256';
  readonly nonce: string; // hex
  readonly signature: string; // hex
  readonly signedAt: number; // epoch ms, covered by the HMAC
}

/**
 * Normalize a key that may arrive as a Buffer or hex/base64 string.
 * Throws when the decoded key is shorter than {@link SNAPSHOT_MIN_KEY_LENGTH_BYTES}.
 */
export function normalizeHmacKey(key: Buffer | string): Buffer {
  let buf: Buffer;
  if (Buffer.isBuffer(key)) {
    buf = key;
  } else if (/^[0-9a-fA-F]+$/.test(key) && key.length % 2 === 0) {
    buf = Buffer.from(key, 'hex');
  } else {
    // Fall back to utf-8 for passphrase-style keys; callers should prefer hex.
    buf = Buffer.from(key, 'utf-8');
  }
  if (buf.length < SNAPSHOT_MIN_KEY_LENGTH_BYTES) {
    throw new Error(
      `snapshot-hmac: key must be >= ${SNAPSHOT_MIN_KEY_LENGTH_BYTES} bytes ` +
      `(received ${buf.length})`,
    );
  }
  return buf;
}

/** Generate a cryptographically random nonce for a fresh checkpoint. */
export function generateNonce(): Buffer {
  return randomBytes(SNAPSHOT_NONCE_LENGTH_BYTES);
}

/**
 * Sign a UTF-8 payload with HMAC-SHA256. The signed material is the
 * concatenation of `nonce || ":" || signedAt || ":" || payload` so the
 * signature binds both replay-defense data and the declared wall-clock
 * timestamp (used by the NonceRegistry freshness check).
 */
export function signSnapshotPayload(
  payload: string,
  key: Buffer | string,
  options?: { readonly nonce?: Buffer; readonly signedAt?: number },
): SnapshotSignatureEnvelope {
  const keyBuf = normalizeHmacKey(key);
  const nonce = options?.nonce ?? generateNonce();
  const signedAt = options?.signedAt ?? Date.now();
  const hmac = createHmac(SNAPSHOT_HMAC_ALGORITHM, keyBuf);
  hmac.update(nonce);
  hmac.update(':');
  hmac.update(String(signedAt));
  hmac.update(':');
  hmac.update(payload, 'utf-8');
  const signature = hmac.digest('hex');
  return {
    algorithm: SNAPSHOT_HMAC_ALGORITHM,
    nonce: nonce.toString('hex'),
    signature,
    signedAt,
  };
}

/**
 * Verify a signature envelope against the payload. Uses timing-safe compare
 * so an attacker cannot distinguish partial-match vs full-mismatch via
 * response-time analysis.
 *
 * Returns `{ ok: true }` on match, `{ ok: false, reason }` with a structured
 * reason otherwise (never throws for bad input — the caller decides fall-back).
 */
export function verifySnapshotPayload(
  payload: string,
  envelope: SnapshotSignatureEnvelope,
  key: Buffer | string,
): { ok: true } | { ok: false; reason: string } {
  if (envelope.algorithm !== SNAPSHOT_HMAC_ALGORITHM) {
    return { ok: false, reason: `unsupported algorithm ${envelope.algorithm}` };
  }
  if (!/^[0-9a-f]+$/i.test(envelope.nonce) || envelope.nonce.length === 0) {
    return { ok: false, reason: 'malformed nonce' };
  }
  if (!/^[0-9a-f]+$/i.test(envelope.signature) || envelope.signature.length === 0) {
    return { ok: false, reason: 'malformed signature' };
  }
  if (typeof envelope.signedAt !== 'number' || !Number.isFinite(envelope.signedAt)) {
    return { ok: false, reason: 'malformed signedAt' };
  }
  let keyBuf: Buffer;
  try {
    keyBuf = normalizeHmacKey(key);
  } catch (err) {
    return { ok: false, reason: (err as Error).message };
  }
  const nonceBuf = Buffer.from(envelope.nonce, 'hex');
  const hmac = createHmac(SNAPSHOT_HMAC_ALGORITHM, keyBuf);
  hmac.update(nonceBuf);
  hmac.update(':');
  hmac.update(String(envelope.signedAt));
  hmac.update(':');
  hmac.update(payload, 'utf-8');
  const expected = hmac.digest();
  let received: Buffer;
  try {
    received = Buffer.from(envelope.signature, 'hex');
  } catch {
    return { ok: false, reason: 'signature hex decode failed' };
  }
  if (received.length !== expected.length) {
    return { ok: false, reason: 'signature length mismatch' };
  }
  if (!timingSafeEqual(received, expected)) {
    return { ok: false, reason: 'signature mismatch' };
  }
  return { ok: true };
}

/**
 * In-memory nonce registry for replay-defense across restore calls within a
 * single runner process. Bound to process lifetime only (no persistent store).
 */
export class NonceRegistry {
  private readonly seen = new Set<string>();

  /**
   * Attempt to register a nonce. Returns true when the nonce is fresh (first
   * time seen) and false when the nonce has already been observed — the
   * caller should then reject the checkpoint as a replay attempt.
   */
  register(nonce: string): boolean {
    if (this.seen.has(nonce)) return false;
    this.seen.add(nonce);
    return true;
  }

  /** Clear all observed nonces. Useful for test isolation. */
  reset(): void {
    this.seen.clear();
  }

  /** Current registry size; used for observability only. */
  get size(): number {
    return this.seen.size;
  }
}
