/**
 * Standardized error codes for the agent system.
 */
export const ErrorCode = {
  TOOL_EXECUTION_ERROR: "TOOL_EXECUTION_ERROR",
  PROVIDER_ERROR: "PROVIDER_ERROR",
  PLUGIN_LOAD_ERROR: "PLUGIN_LOAD_ERROR",
  SECURITY_ERROR: "SECURITY_ERROR",
  TRANSPORT_ERROR: "TRANSPORT_ERROR",
  TRANSPORT_CONNECTION_ERROR: "TRANSPORT_CONNECTION_ERROR",
  TRANSPORT_SEND_ERROR: "TRANSPORT_SEND_ERROR",
  SESSION_ERROR: "SESSION_ERROR",
  SESSION_NOT_FOUND: "SESSION_NOT_FOUND",
  SESSION_INVALID_OPERATION: "SESSION_INVALID_OPERATION",
  CONFIG_ERROR: "CONFIG_ERROR",
  CONFIG_VALIDATION_ERROR: "CONFIG_VALIDATION_ERROR",
  MCP_CONNECTION_ERROR: "MCP_CONNECTION_ERROR",
  MCP_PROTOCOL_ERROR: "MCP_PROTOCOL_ERROR",
  MCP_TOOL_CALL_ERROR: "MCP_TOOL_CALL_ERROR",
} as const;

export type ErrorCodeValue = (typeof ErrorCode)[keyof typeof ErrorCode];
