#!/usr/bin/env python3
"""source_diff_check.py — Coordinator G5 gate: source-relevant diff between 2 release dirs.

Used by coordinator G5 gate to enforce: a release that has zero source-relevant
diff vs its predecessor is either (a) intentionally doc-only and must be tagged
as such in delivery_report.md, or (b) auto-rejected as an empty version bump.

Excluded paths (regenerated test artifacts / lockfiles / build):
    package-lock.json, pnpm-lock.yaml (lockfiles)
    *.tsbuildinfo, dist/, node_modules/, .turbo/
    audit-trail-*.jsonl, assertion-coverage.json (regenerated by pnpm test)

Usage:
    source_diff_check.py <release_dir_A> <release_dir_B>
    source_diff_check.py --json <A> <B>
    source_diff_check.py --strict <A> <B>  # exit 1 if doc-only (no source diff)

Exit codes:
    0 = source diff present
    1 = no source diff (doc-only / empty version bump)
    2 = error (missing dir, etc.)
"""
import argparse
import filecmp
import json
import os
import sys
from pathlib import Path

EXCLUDED_NAMES = {
    "package-lock.json",
    "pnpm-lock.yaml",
    "audit-trail-test-agent.jsonl",
    "audit-trail-smoke-chatgpt.jsonl",
    "assertion-coverage.json",
}
EXCLUDED_DIR_PARTS = {"node_modules", "dist", ".turbo", "__pycache__", ".pytest_cache"}
EXCLUDED_SUFFIXES = {".tsbuildinfo"}


def is_excluded(path: Path) -> bool:
    if path.name in EXCLUDED_NAMES:
        return True
    if any(part in EXCLUDED_DIR_PARTS for part in path.parts):
        return True
    if path.suffix in EXCLUDED_SUFFIXES:
        return True
    if path.name.endswith(".jsonl") and "audit-trail" in path.name:
        return True
    return False


def collect_files(root: Path) -> set[Path]:
    out: set[Path] = set()
    for p in root.rglob("*"):
        if not p.is_file():
            continue
        rel = p.relative_to(root)
        if is_excluded(rel):
            continue
        out.add(rel)
    return out


def diff_release(a: Path, b: Path) -> dict:
    if not a.is_dir() or not b.is_dir():
        raise FileNotFoundError(f"Both args must be directories: {a}, {b}")
    files_a = collect_files(a)
    files_b = collect_files(b)
    only_a = sorted(str(p) for p in files_a - files_b)
    only_b = sorted(str(p) for p in files_b - files_a)
    changed: list[str] = []
    for rel in sorted(files_a & files_b):
        if not filecmp.cmp(a / rel, b / rel, shallow=False):
            changed.append(str(rel))
    return {
        "only_in_a": only_a,
        "only_in_b": only_b,
        "changed": changed,
        "total_diff_count": len(only_a) + len(only_b) + len(changed),
    }


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("a", help="First release dir")
    ap.add_argument("b", help="Second release dir")
    ap.add_argument("--json", action="store_true", help="Emit JSON")
    ap.add_argument("--strict", action="store_true", help="Exit 1 if doc-only")
    args = ap.parse_args()
    try:
        result = diff_release(Path(args.a), Path(args.b))
    except FileNotFoundError as e:
        print(f"error: {e}", file=sys.stderr)
        return 2
    if args.json:
        print(json.dumps(result, indent=2))
    else:
        print(f"only_in_a: {len(result['only_in_a'])}")
        print(f"only_in_b: {len(result['only_in_b'])}")
        print(f"changed:   {len(result['changed'])}")
        print(f"total:     {result['total_diff_count']}")
        if result["changed"]:
            for c in result["changed"]:
                print(f"  ~ {c}")
        for o in result["only_in_a"]:
            print(f"  < {o}")
        for o in result["only_in_b"]:
            print(f"  > {o}")
    if args.strict and result["total_diff_count"] == 0:
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
